export const SHEETS = {
  caller: {
    table: "sheet_caller",
    editableFields: new Set([
      "notes",
      "call_status",
      "status",
      "seller_phone",
      "real_value",
      "purch_value",
      "vin",
      "color",
      "lowest_price",
      "follow_up_date",
      "location",
      "odometer",
      "ad_link",
    ]),
    event: "sheet:caller:update",
  },

  lead: {
    table: "sheet_leads",
    editableFields: new Set([
      "seller_name",
      "purch_address",
      "postal_code",
      "odometer",
      "year",
      "make",
      "model",
      "vin",
      "color",
      "purch_date",
      "purch_price",
      "extra_cost",
      "total_cost",
      "sell_price",
      "p_l",
      "sell_date",
      "purch_name",
      "sell_address",
      "file",
      "status",
    ]),
    event: "sheet:lead:update",
  },

  // ibrahim: {
  //   table: "sheet_ibrahim",
  //   editableFields: new Set([
  //     "notes",
  //     "call_status",
  //     "status",
  //     "seller_phone",
  //     "real_value",
  //     "purch_value",
  //     "vin",
  //     "color",
  //     "lowest_price",
  //     "follow_up_date",
  //   ]),
  //   event: "sheet:ibrahim:update",
  // },
  // omar: {
  //   table: "sheet_omar",
  //   editableFields: new Set([
  //     "notes",
  //     "call_status",
  //     "status",
  //     "seller_phone",
  //     "real_value",
  //     "purch_value",
  //     "vin",
  //     "color",
  //     "lowest_price",
  //     "follow_up_date",
  //   ]),
  //   event: "sheet:omar:update",
  // },
} as const;

export type SheetKey = keyof typeof SHEETS;
